### ISSUE TITLE
Named node doesn't start due to java.net.UnknownHostException errors

### ISSUE THREAD

**Issue by rporres** [apache-spark-on-k8s/kubernetes-HDFS#13]
I'm testing the charts using a 1.5.2 k8s cluster in my laptop using [kubernetes on vagrant](https://coreos.com/kubernetes/docs/latest/kubernetes-on-vagrant.html) CoreOS project.

After setting up `/etc/resolv.conf` config map, I install named node chart but it fails to start

```
17/06/27 13:21:03 ERROR impl.MetricsSystemImpl: Error getting localhost name. Using 'localhost'...
java.net.UnknownHostException: w1: w1: Temporary failure in name resolution
	at java.net.InetAddress.getLocalHost(InetAddress.java:1505)
	at org.apache.hadoop.metrics2.impl.MetricsSystemImpl.getHostname(MetricsSystemImpl.java:548)
	at org.apache.hadoop.metrics2.impl.MetricsSystemImpl.configureSystem(MetricsSystemImpl.java:487)
	at org.apache.hadoop.metrics2.impl.MetricsSystemImpl.configure(MetricsSystemImpl.java:483)
	at org.apache.hadoop.metrics2.impl.MetricsSystemImpl.start(MetricsSystemImpl.java:189)
	at org.apache.hadoop.metrics2.impl.MetricsSystemImpl.init(MetricsSystemImpl.java:164)
	at org.apache.hadoop.metrics2.lib.DefaultMetricsSystem.init(DefaultMetricsSystem.java:54)
	at org.apache.hadoop.metrics2.lib.DefaultMetricsSystem.initialize(DefaultMetricsSystem.java:50)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.createNameNode(NameNode.java:1487)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.main(NameNode.java:1554)
Caused by: java.net.UnknownHostException: w1: Temporary failure in name resolution
	at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
	at java.net.InetAddress.getLocalHost(InetAddress.java:1500)
```

As you can see, the hostname it is trying to resolve is `w1` instead of what I was expecting `hdfs-namenode-0.hdfs-namenode.default.svc.cluster.local`. Taking a further look into it, this is due to the setting `hostNetwork: true` that forces the container to get the node hostname. Apparently this is a [feature](https://github.com/kubernetes/kubernetes/pull/12980). I feel that there's some incompatibility between that and the stateful sets pod hostnames...

I've been able to setup the cluster by replacing your `/etc/resolv.conf` config map by a `/etc/hosts` map that contains the real IP address of the nodes and by replacing the `CORE_CONF_fs_defaultFS` value in datanode chart using the name of the node that's running the name node.

Have you experienced problems similar to what I'm having?

I have troubles understanding how the setup has worked fine for you due to the following points

* Is your kube-dns resolving node names?
* Is your kube-dns resolving correctly `hdfs-namenode-0.hdfs-namenode.default.svc.cluster.local`?

as in my case it was not doing any of those tasks.

Maybe these issues are related to the fact that I'm using k8s 1.5.2 and https://github.com/kubernetes/kubernetes/pull/29378 is not there yet. Anyway I somehow feel that using DNS for localhost name resolution is not a good idea as named nodes (and I assume data nodes) would fail to start if kube-dns is not available. Would it be better/safer to use a static `/etc/hosts` config map?

Thanks a lot for putting together these charts. They've been quite helpful

**Comment by kimoonkim** [comment]
@rporres Thanks for trying out the k8s HDFS! And thanks for reporting this issue.

There is an implicit DNS resolution requirement for the cluster node names. Since the namenode daemon uses `hostNetwork`, it sees itself associated with the cluster node hostname as far as DNS is concerned. `hdfs-namenode-0.hdfs-namenode.default.svc.cluster.local` is used only by the datanodes and HDFS clients when *they* see the namenode.

However, I think the cluster node hostname is not directly resolved by kube-dns, which only concerns k8s service names. Rather, I believe kube-dns will fall back to the DNS server in charge of your physical hosts.

So I suspect your issue has to do with this fallback mechanism somehow broken. I saw errors similar to yours when I set up a cluster on AWS EC2 and forgot to append the EC2 domain name to the `search` line in `/etc/resolv.conf` config map. Step 2 of [hdfs-resolv-conf README.md](https://github.com/apache-spark-on-k8s/kubernetes-HDFS/blob/master/charts/hdfs-resolv-conf/README.md) has more details on this.

Can you post `/etc/resolv.conf` config map content, maybe redacted of mask sensitive information if any?

Another thing to suspect is if the cluster node names are properly assigned. Hadoop expects the local host names to match the fully qualified host names. i.e. put long host names as primary entry in `/etc/hostname` or `/etc/hosts`. Avoid short host names or `localhost`.

Mine from a k8s node looks like this:
```
$ cat /etc/hosts
127.0.0.1       localhost.localdomain localhost
::1     localhost6.localdomain6 localhost6
192.168.6.157    kube-n1.pepperdata.com kube-n1

$ cat /etc/hostname
kube-n1.pepperdata.com
```

A quick way to tell is to check `$ /usr/bin/hostname` and `$ /usr/bin/hostname -A` print out the same long host name. i.e. `node1.mycompany.com`, not `node1`. Can you also try this out?

Again, thanks for trying out kube-hdfs. Please let us know if you have further issues.

**Comment by rporres** [comment]
Hi @kimoonkim thanks for your reply

I guess my problem is that there's no DNS that resolves the physical node names as they're just virtual machines in my laptop, hence there's no domain to configure in hdfs-resolv-conf chart.

```
 $ kubectl run -i -t --rm busybox --image=busybox --restart=Never      --command -- cat /etc/resolv.conf
search default.svc.cluster.local svc.cluster.local cluster.local
nameserver 10.3.0.10
options ndots:5
```
As for the node names, this comes from one of the workers
```
core@w1 ~ $ egrep -v '^#|^$' /etc/hosts
127.0.0.1	localhost
::1		localhost
core@w1 ~ $ /usr/bin/hostname
w1
core@w1 ~ $ /usr/bin/hostname -A
/usr/bin/hostname: invalid option -- 'A'
```
Node names are not properly set in `/etc/hosts`... Maybe that has something to do, I will try and come back to you.

As for my fix, I've removed the `resolv.conf` config map and replaced it by a `hosts` config map that adds a `/etc/hosts` file in every HDFS node, e.g
```
$ kubectl exec -it "hdfs-namenode-0" -- cat /etc/hosts
172.17.4.101 c1
172.17.4.201 w1
172.17.4.202 w2
```

As far as I can see, cluster is up and running ok, I can access management web in named node port 50070 and I've been able to create files through hdfs command...

**Comment by rporres** [comment]
When I add the node hosts IPs to the `/etc/hosts` file in the nodes things work fine without any config mapping, as it looks that container uses the node `hosts` file

**Comment by rporres** [comment]
And now I can add back the `resolv.conf` mapping to have the pods use `kube-dns` to be able to resolve `hdfs-namenode-0.hdfs-namenode.default.svc.cluster.local` and use it in the datanode chart in its form.

I guess I got confused about the extent of the usage of the kube-dns and the fact that in my case I didn't have an external resolving the node names that kube-dns would forward requests.

It also didn't help that [kubernetes on vagrant](https://coreos.com/kubernetes/docs/latest/kubernetes-on-vagrant.html) didn't set up properly the `hosts` file and it created a weird error...

Thanks for your help!

**Comment by kimoonkim** [comment]
That's great. I hope it wasn't too much trouble. Glad that I could help. Thanks for trying out kube-hdfs.
