### ISSUE TITLE
Spark data locality in standalone?

### ISSUE THREAD

**Issue by jpiper** [apache-spark-on-k8s/kubernetes-HDFS#17]
I've got HDFS up and running and can run the example hadoop container and `cat` a file and see I'm always coming from the local node (woohoo!)

I just want to confirm, in order to have data locality I need to be running kubespark (spark standalone in kubernetes won't work?)

**Comment by ssuchter** [comment]
That’s correct - there were modifications to Spark to make locality work.

Sean

On July 26, 2017 at 9:41:30 PM, Jason Piper (notifications@github.com)
wrote:

I've got HDFS up and running and can run the example hadoop container and
cat a file and see I'm always coming from the local node (woohoo!)

I just want to confirm, in order to have data locality I need to be running
kubespark (spark standalone in kubernetes won't work?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/apache-spark-on-k8s/kubernetes-HDFS/issues/17>, or mute
the thread

**Comment by jpiper** [comment]
Fantastic, I thought so! I'm just about to give it all a spin, fingers crossed!
