### ISSUE TITLE
Discuss K8s HDFS in Google Cloud Engine

### ISSUE THREAD

**Issue by kimoonkim** [apache-spark-on-k8s/kubernetes-HDFS#5]
As a follow-up of #1, I have applied our HDFS to a K8s cluster in Google Cloud Engine. Please see this doc describing the experience, http://tiny.pepperdata.com/hdfs-k8s-gke, for details. The high level summary is:
  - We successfully launched our HDFS in K8s on Google Container Engine. There were some minor issues that are marked as TODOs in the doc.
  - We also observed, unlike overlay networks, GKE network lets the namenode see clients’ virtual pod IPs even though the namenode itself is on `hostNetwork`. This makes us believe that the namenode locality issue described in http://tiny.pepperdata.com/k8s-hdfs-locality is real in GKE.

CC @foxish @ash211 @lins05

**Comment by foxish** [comment]
Thanks for the detailed analysis on the GKE situation. I was having a discussion with @owensk and we were thinking that in the cloud case, we should probably figure out how much of an issue locality really is (quantify the impact). Because of the sophistication of the networks, it is possible that the lack of locality does not impact performance substantially.
 
I remember that you guys had wanted to run some large-scale spark jobs making use of HDFS; I think we might want to do that sooner than later, before we invest too much time in perfecting the plugin that you're writing.
On-prem, I do agree that the HDFS locality issue will likely be more pronounced and needs to be solved (and as @lins05 pointed out, hostNetwork does give us quite a bit). 

We may also want to test against a couple of different types of overlay networks to ensure that we're seeing consistent results. @kimoonkim @ssuchter what do you think?

**Comment by kimoonkim** [comment]
@foxish The suggestion sounds good to me. I was only hoping to ensure the topology plugin is not a dead-end, and my current prototype is a proof-of-concept enough for that. I'll start to think about the experiment in more details.

**Comment by kimoonkim** [comment]
With the progress we made on [Spark issue #206 comment](https://github.com/apache-spark-on-k8s/spark/issues/206#issuecomment-300546376), I think we can close this issue. We learned so far that the namenode topology plugin is needed only in GKE.

See the Spark issue #206 comment link above for details.
